name: pipeline
on: [workflow_dispatch, push]

jobs:
  buildApp:
    name: Build - App
    runs-on: ubuntu-20.04
    steps:
      - name: Scan Container
        uses: Azure/container-scan@v0
        with:
          image-name: mcr.microsoft.com/playwright:focal
          severity-threshold: CRITICAL
